### ISSUE TITLE
Validation on model.save()?

### ISSUE THREAD

**Issue by LaundroMat** [surenkov/django-pydantic-field#25]
First of all, great idea -- this will give me less to worry about when working with JSON fields.

I just ran a quick test with one of my models, and am I right that schema validation only occurs when *loading* the model data? So I should always use the schema to alter the model JSON data and not assign properties directly? (It's not that I mind, I just want to know for sure).

```
class SettingsSchema(pydantic.BaseModel):
    private: bool = False

class Item(models.Model):
    settings: SettingsSchema = SchemaField(default=SettingsSchema)

def test_settings_validation():
    item = Item()
    item.settings.private= 'not a bool'
    item.save()
    item.refresh_from_db()
```

Test output:
```
def test_item_settings_validation():
        item = Item()
        item.settings.private = 'not a bool'
        item.save()
>     item.refresh_from_db()
...
validation_error = ValidationError(model='FieldSchema[SettingsSchema]', errors=[{'loc': ('__root__', 'private'), 'msg': 'value could not be parsed to a boolean', 'type': 'type_error.bool'}])
```

**Comment by surenkov** [comment]
Hi @LaundroMat, thank you for opening that issue!

Generally, validation occurs on django models' field assignment (regardless of either it has happened during instance data loading or direct assignment).

In your case, the inconsistency occurred because the instance's field assignment actually did not happen -- the assignment was on a nested pydantic model's field.

With current state of the art, I would expect two options how this could be mitigated:
- either assign the whole settings model to `item.settings` field, something like:
  ```python
  item.settings = item.settings.copy(update={"private": "not a bool"})
  ```
- or, by enabling `validate_assignment` option in pydantic model config: <img width="926" alt="Screenshot 2023-07-24 at 11 40 32" src="https://github.com/surenkov/django-pydantic-field/assets/942909/3e596d02-b5c1-4552-bb9a-a1475ace977b">

This might be a good thing to consider for the next major update with pydantic v2 support.

**Comment by LaundroMat** [comment]
Thanks for taking the time to reply so thoroughly (even though it's not actually a django-pydantic-field related thing). FYI, I'll go for option 1, as `validate_assignment` does not call the root validator (see https://github.com/pydantic/pydantic/issues/3821; this'll be fixed in pydantic v2, but I'm not ready for that upgrade yet).

Keep up the good work!
